// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieLibrary.Data;

#nullable disable

namespace MovieLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230716101304_addtitonalSeed")]
    partial class addtitonalSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "341743f0 - asd2–42de - afbf - 59kmkkmk72cf6",
                            ConcurrencyStamp = "341743f0 - asd2–42de - afbf - 59kmkkmk72cf6",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "3619fba3-c4f1-40fb-a55e-6511795cfa19",
                            ConcurrencyStamp = "c350acf4-5b35-4851-acec-c33168a80fd0",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "78d40ac6-e0dd-48be-83ee-45021caf491c",
                            ConcurrencyStamp = "fd07f3ad-724b-4df9-92cd-bba43b762cf7",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            RoleId = "341743f0 - asd2–42de - afbf - 59kmkkmk72cf6"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MovieLibrary.Models.Actors.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            FirstName = "Margot",
                            Gender = "Female",
                            LastName = "Robbie"
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            FirstName = "Chris",
                            Gender = "Male",
                            LastName = "Hemsworth"
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            FirstName = "Golshifteh",
                            Gender = "Female",
                            LastName = "Farahani"
                        },
                        new
                        {
                            Id = 4,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            FirstName = "Adam",
                            Gender = "Male",
                            LastName = "Bessa"
                        },
                        new
                        {
                            Id = 5,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            FirstName = "Ryder",
                            Gender = "Male",
                            LastName = "Lerum"
                        },
                        new
                        {
                            Id = 6,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            FirstName = "Bryon",
                            Gender = "Male",
                            LastName = "Lerum"
                        },
                        new
                        {
                            Id = 7,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            FirstName = "Keanu",
                            Gender = "Male",
                            LastName = "Reeves"
                        },
                        new
                        {
                            Id = 8,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            FirstName = "Laurence",
                            Gender = "Female",
                            LastName = "Fishburne"
                        },
                        new
                        {
                            Id = 9,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            FirstName = "George",
                            Gender = "Male",
                            LastName = "Georgiou"
                        },
                        new
                        {
                            Id = 10,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            FirstName = "Tim",
                            Gender = "Male",
                            LastName = "Robbins"
                        },
                        new
                        {
                            Id = 11,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            FirstName = "Morgan",
                            Gender = "Male",
                            LastName = "Freeman"
                        },
                        new
                        {
                            Id = 12,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            FirstName = "Bob",
                            Gender = "Male",
                            LastName = "Guton"
                        });
                });

            modelBuilder.Entity("MovieLibrary.Models.Actors.ActorAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActorAwards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Best Actress"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Screen Actors Guild Award"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Academy Award (Oscar)"
                        },
                        new
                        {
                            Id = 4,
                            Name = "European Film Award"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Best Actor"
                        });
                });

            modelBuilder.Entity("MovieLibrary.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PictureSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            AccessFailedCount = 0,
                            Age = 30,
                            ConcurrencyStamp = "6bfd3179-e93f-455c-9133-d5515c8e9d9b",
                            Email = "admin@admin.bg",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.BG",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEDgAtU8D7Ht2RrfDdHanwaX53AHCUK63fkttc1IoH7yIf+mvDYOC5GZapRVItxHvlg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dddbf736-d03c-4c93-8a57-8dd9da07e350",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("MovieLibrary.Models.Movies.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<string>("AppUserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumAge")
                        .HasColumnType("int");

                    b.Property<string>("PosterSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsersRated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ProducerId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accepted = true,
                            AppUserEmail = "admin@admin.bg",
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            Budget = 100000000,
                            Category = "Action",
                            Description = "Tyler Rake, a fearless black market mercenary, embarks on the most deadly extraction of his career when he's enlisted to rescue the kidnapped son of an imprisoned international crime lord.",
                            MinimumAge = 18,
                            PosterSource = "~/images/posters/extraction2020.jpg",
                            ProducerId = 9,
                            Rating = 0.0,
                            ReleaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Extraction",
                            TrailerUrl = "L6P3nI6VnlY",
                            UsersRated = 0
                        },
                        new
                        {
                            Id = 2,
                            Accepted = true,
                            AppUserEmail = "admin@admin.bg",
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            Budget = 300000000,
                            Category = "Action",
                            Description = "After barely surviving his grievous wounds from his mission in Dhaka, Bangladesh, Tyler Rake is back, and his team is ready to take on their next mission.",
                            MinimumAge = 18,
                            PosterSource = "~/images/posters/extraction2023.jpg",
                            ProducerId = 9,
                            Rating = 0.0,
                            ReleaseDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Extraction 2",
                            TrailerUrl = "Y274jZs5s7s",
                            UsersRated = 0
                        },
                        new
                        {
                            Id = 3,
                            Accepted = true,
                            AppUserEmail = "admin@admin.bg",
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            Budget = 450000000,
                            Category = "Action",
                            Description = "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
                            MinimumAge = 18,
                            PosterSource = "~/images/posters/johnwich4.jpeg",
                            ProducerId = 10,
                            Rating = 0.0,
                            ReleaseDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "John Wick: Chapter 4",
                            TrailerUrl = "qEVUtrk8_B4",
                            UsersRated = 0
                        },
                        new
                        {
                            Id = 4,
                            Accepted = true,
                            AppUserEmail = "admin@admin.bg",
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            Budget = 990000000,
                            Category = "Western",
                            Description = "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
                            MinimumAge = 16,
                            PosterSource = "~/images/posters/shawshank.jpg",
                            ProducerId = 11,
                            Rating = 4.7000000000000002,
                            ReleaseDate = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption",
                            TrailerUrl = "6hB3S9bIaco",
                            UsersRated = 1000
                        });
                });

            modelBuilder.Entity("MovieLibrary.Models.Movies.MovieAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MovieAwards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Emmy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Golden Globe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Academy Award (Oscar)"
                        },
                        new
                        {
                            Id = 4,
                            Name = "European Film Award"
                        },
                        new
                        {
                            Id = 5,
                            Name = "British Academy Film Award"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Filmfare Award"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Critics' Choice Movie"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Best Feature Film"
                        });
                });

            modelBuilder.Entity("MovieLibrary.Models.Movies.MovieComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieComments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            MovieId = 1,
                            PostedTime = new DateTime(2023, 7, 16, 10, 13, 4, 160, DateTimeKind.Utc).AddTicks(8861),
                            Text = "Very good movie!"
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            MovieId = 1,
                            PostedTime = new DateTime(2023, 7, 16, 10, 13, 4, 160, DateTimeKind.Utc).AddTicks(8863),
                            Text = "I can agree too"
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            MovieId = 1,
                            PostedTime = new DateTime(2023, 7, 16, 10, 13, 4, 160, DateTimeKind.Utc).AddTicks(8864),
                            Text = "I want to watch the next one"
                        },
                        new
                        {
                            Id = 4,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            MovieId = 2,
                            PostedTime = new DateTime(2023, 7, 16, 10, 13, 4, 160, DateTimeKind.Utc).AddTicks(8865),
                            Text = "I dont like it that much"
                        },
                        new
                        {
                            Id = 5,
                            AppUserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            MovieId = 3,
                            PostedTime = new DateTime(2023, 7, 16, 10, 13, 4, 160, DateTimeKind.Utc).AddTicks(8865),
                            Text = "Sadly its the last movie from the series"
                        });
                });

            modelBuilder.Entity("MovieLibrary.Models.Movies.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Producers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Michael Mann"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jerry Bruckheimer"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Spike LeeSpike Lee"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Irwin Winkler"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dana Brunetti"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kathleen Kennedy"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sam Hargrave"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Chad Stahelski"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Frank Darabont"
                        });
                });

            modelBuilder.Entity("MovieLibrary.Models.Relations.Actor_ActorAward", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("ActorAwardId")
                        .HasColumnType("int");

                    b.HasKey("ActorId", "ActorAwardId");

                    b.HasIndex("ActorAwardId");

                    b.ToTable("Actor_ActorAwards");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            ActorAwardId = 1
                        },
                        new
                        {
                            ActorId = 11,
                            ActorAwardId = 2
                        });
                });

            modelBuilder.Entity("MovieLibrary.Models.Relations.Actor_Movie", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("ActorId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("Actors_Movies");

                    b.HasData(
                        new
                        {
                            ActorId = 2,
                            MovieId = 2
                        },
                        new
                        {
                            ActorId = 3,
                            MovieId = 2
                        },
                        new
                        {
                            ActorId = 4,
                            MovieId = 2
                        },
                        new
                        {
                            ActorId = 2,
                            MovieId = 1
                        },
                        new
                        {
                            ActorId = 5,
                            MovieId = 1
                        },
                        new
                        {
                            ActorId = 6,
                            MovieId = 1
                        },
                        new
                        {
                            ActorId = 7,
                            MovieId = 3
                        },
                        new
                        {
                            ActorId = 8,
                            MovieId = 3
                        },
                        new
                        {
                            ActorId = 9,
                            MovieId = 3
                        },
                        new
                        {
                            ActorId = 10,
                            MovieId = 4
                        },
                        new
                        {
                            ActorId = 11,
                            MovieId = 4
                        },
                        new
                        {
                            ActorId = 12,
                            MovieId = 4
                        });
                });

            modelBuilder.Entity("MovieLibrary.Models.Relations.BucketList", b =>
                {
                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("AppUserId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("BucketLists");
                });

            modelBuilder.Entity("MovieLibrary.Models.Relations.Favourite", b =>
                {
                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("AppUserId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("MovieLibrary.Models.Relations.Movie_MovieAward", b =>
                {
                    b.Property<int>("MovieAwardId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("MovieAwardId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("Movie_MovieAwards");

                    b.HasData(
                        new
                        {
                            MovieAwardId = 3,
                            MovieId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MovieLibrary.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MovieLibrary.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieLibrary.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MovieLibrary.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieLibrary.Models.Actors.Actor", b =>
                {
                    b.HasOne("MovieLibrary.Models.AppUser", "AppUser")
                        .WithMany("Actors")
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("MovieLibrary.Models.Movies.Movie", b =>
                {
                    b.HasOne("MovieLibrary.Models.AppUser", "AppUser")
                        .WithMany("Movies")
                        .HasForeignKey("AppUserId");

                    b.HasOne("MovieLibrary.Models.Movies.Producer", "Producer")
                        .WithMany()
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("MovieLibrary.Models.Movies.MovieComment", b =>
                {
                    b.HasOne("MovieLibrary.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieLibrary.Models.Movies.Movie", "Movie")
                        .WithMany("MovieComments")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieLibrary.Models.Relations.Actor_ActorAward", b =>
                {
                    b.HasOne("MovieLibrary.Models.Actors.ActorAward", "ActorAward")
                        .WithMany("Actor_ActorAwards")
                        .HasForeignKey("ActorAwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieLibrary.Models.Actors.Actor", "Actor")
                        .WithMany("Actor_ActorAwards")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("ActorAward");
                });

            modelBuilder.Entity("MovieLibrary.Models.Relations.Actor_Movie", b =>
                {
                    b.HasOne("MovieLibrary.Models.Actors.Actor", "Actor")
                        .WithMany("ActorsMovies")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieLibrary.Models.Movies.Movie", "Movie")
                        .WithMany("ActorsMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieLibrary.Models.Relations.BucketList", b =>
                {
                    b.HasOne("MovieLibrary.Models.AppUser", "AppUser")
                        .WithMany("BucketLists")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieLibrary.Models.Movies.Movie", "Movie")
                        .WithMany("BucketLists")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieLibrary.Models.Relations.Favourite", b =>
                {
                    b.HasOne("MovieLibrary.Models.AppUser", "AppUser")
                        .WithMany("Favourites")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieLibrary.Models.Movies.Movie", "Movie")
                        .WithMany("Favourites")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieLibrary.Models.Relations.Movie_MovieAward", b =>
                {
                    b.HasOne("MovieLibrary.Models.Movies.MovieAward", "MovieAward")
                        .WithMany("Movie_MovieAwards")
                        .HasForeignKey("MovieAwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieLibrary.Models.Movies.Movie", "Movie")
                        .WithMany("Movie_MovieAwards")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("MovieAward");
                });

            modelBuilder.Entity("MovieLibrary.Models.Actors.Actor", b =>
                {
                    b.Navigation("Actor_ActorAwards");

                    b.Navigation("ActorsMovies");
                });

            modelBuilder.Entity("MovieLibrary.Models.Actors.ActorAward", b =>
                {
                    b.Navigation("Actor_ActorAwards");
                });

            modelBuilder.Entity("MovieLibrary.Models.AppUser", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("BucketLists");

                    b.Navigation("Favourites");

                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieLibrary.Models.Movies.Movie", b =>
                {
                    b.Navigation("ActorsMovies");

                    b.Navigation("BucketLists");

                    b.Navigation("Favourites");

                    b.Navigation("MovieComments");

                    b.Navigation("Movie_MovieAwards");
                });

            modelBuilder.Entity("MovieLibrary.Models.Movies.MovieAward", b =>
                {
                    b.Navigation("Movie_MovieAwards");
                });
#pragma warning restore 612, 618
        }
    }
}
